#ifndef SERIALCONSTANTS_h
#define SERIALCONSTANTS_h

#define START_BYTE 0xDE

#define COMMAND_SET_PORT 0x53 // 'S'
#define COMMAND_PRINT_IDENTITY 0x49 //'I'
#define COMMAND_DIRECTION 0x44 //D
#define COMMAND_POWER 0x50//P
#define COMMAND_DRIVE_READ 0x52 //R
#define COMMAND_SET_ENCODER  0x45
#define IDENTITY "STEERING"
#define ENCODER_MOTOR  0x4D
#define ENCODER_STEERING 0x53
#define BOUD_RATE 9600

#endif