#ifndef CONSTANTS_h
#define CONSTANTS_h

#define START_BYTE 0xDE

#define COMMAND_SET_PORT 0x53 // 'S'
#define COMMAND_PRINT_IDENTITY 0x49 //'I'
#define COMMAND_DIRECTION 0x44 //D
#define COMMAND_DRIVE_POWER 0x50//P
#define COMMAND_DRIVE_READ 0x52 //R

#define DIRECTION_STATE_FORWARD 0x46
#define DIRECTION_STATE_BACKWARDS 0x42

#define IDENTITY "DRIVE"

#define BOUD_RATE 9600

#endif